image: node:15-alpine

stages:
  - build

build:
  stage: build
  allow_failure: false
  only:
    - master

  cache:
    paths:
      - .yarn

  before_script:
    - export TZ=Europe/Moscow
    - apk add --update git
    - git config --global push.default simple
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "${CI_REPOSITORY_URL}"
    - git checkout master
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn install --pure-lockfile --cache-folder .yarn

  script:
    - yarn build &&
      yarn lerna publish --conventional-commits --yes
  #after_script:
  #  - yarn ci:coveralls
