image: node:15-slim

stages:
  - build

before_script:
  - npm i -g yarn
  - export PATH=`yarn global bin`:$PATH
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

build:
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn build
