image: node:15-slim

stages:
  - build

build:
  stage: build

  cache:
    paths:
      - .yarn

  before_script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn install --cache-folder .yarn

  script:
    - yarn install --pure-lockfile
    - yarn build
    - echo Hello
