language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - "15"

before_install:
  - npm i -g yarn
  - export PATH=`yarn global bin`:$PATH
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - yarn global add greenkeeper-lockfile@2
  - yarn global add lerna

install: yarn install --pure-lockfile

before_script:
  - export TZ=Europe/Moscow
  - greenkeeper-lockfile-update
  - git config --global push.default simple
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://${GH_TOKEN}@github.com/izatop/reform.git
  - git checkout master

script: yarn lint && yarn ci:build && yarn test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - lerna publish --conventional-commits --yes && yarn ci:coveralls

branches:
  only:
    - master
