export const data = [
    {
        index: 1,
        isActive: true,
        balance: 2312.12,
        picture: "http://placehold.it/32x32",
        age: 20,
        name: "Graves Page",
        gender: "male",
        company: "SENMAO",
        email: "gravespage@senmao.com",
        phone: "+1 (840) 414-3738",
    },
    {
        index: 2,
        isActive: true,
        balance: 1352.62,
        picture: "http://placehold.it/32x32",
        age: 38,
        name: "Blanca William",
        gender: "female",
        company: "COGNICODE",
        email: "blancawilliam@cognicode.com",
        phone: "+1 (921) 541-2769",
    },
    {
        index: 3,
        isActive: false,
        balance: 2210.49,
        picture: "http://placehold.it/32x32",
        age: 38,
        name: "Gamble Lawson",
        gender: "male",
        company: "ETERNIS",
        email: "gamblelawson@eternis.com",
        phone: "+1 (923) 463-3318",
    },
    {
        index: 4,
        isActive: true,
        balance: 3133.60,
        picture: "http://placehold.it/32x32",
        age: 39,
        name: "Gates Beasley",
        gender: "male",
        company: "PIVITOL",
        email: "gatesbeasley@pivitol.com",
        phone: "+1 (983) 600-3201",
    },
    {
        index: 5,
        isActive: true,
        balance: 3952.90,
        picture: "http://placehold.it/32x32",
        age: 40,
        name: "Marisol Thompson",
        gender: "female",
        company: "ISBOL",
        email: "marisolthompson@isbol.com",
        phone: "+1 (914) 510-3941",
    },
];
